name: .NET Testing Workflow (Mac Intel)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Testing/Testing.csproj

    - name: Build Testing project
      run: dotnet build Testing/Testing.csproj --configuration Release --no-restore

    - name: Run Tests
      run: dotnet run --project Testing/Testing.csproj --configuration Release
